### ISSUE TITLE
stellar protocol has changed, check if sdk needs to be upgraded

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#170]
my sanity script failed:
```
./issued.py > issued.txt
Traceback (most recent call last):
  File "./issued.py", line 52, in <module>
    list_issued()
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/scripts/env/lib/python3.7/site-packages/click/core.py", line 775, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/scripts/env/lib/python3.7/site-packages/click/core.py", line 728, in main
    rv = self.invoke(ctx)
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/scripts/env/lib/python3.7/site-packages/click/core.py", line 981, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/scripts/env/lib/python3.7/site-packages/click/core.py", line 568, in invoke
    return callback(*args, **kwargs)
  File "./issued.py", line 42, in list_issued
    response_transaction["envelope_xdr"], stellar_sdk.Network.PUBLIC_NETWORK_PASSPHRASE
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/scripts/env/lib/python3.7/site-packages/stellar_sdk/transaction_envelope.py", line 161, in from_xdr
    xdr_object = Xdr.types.TransactionEnvelope.from_xdr(xdr)
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/scripts/env/lib/python3.7/site-packages/stellar_sdk/xdr/StellarXDR_type.py", line 2606, in from_xdr
    return xdr_unpacked.unpack_TransactionEnvelope()
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/scripts/env/lib/python3.7/site-packages/stellar_sdk/xdr/StellarXDR_pack.py", line 3460, in unpack_TransactionEnvelope
    data.tx = self.unpack_Transaction()
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/scripts/env/lib/python3.7/site-packages/stellar_sdk/xdr/StellarXDR_pack.py", line 3425, in unpack_Transaction
    data.sourceAccount = self.unpack_AccountID()
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/scripts/env/lib/python3.7/site-packages/stellar_sdk/xdr/StellarXDR_pack.py", line 2399, in unpack_PublicKey
    data.type = self.unpack_PublicKeyType()
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/scripts/env/lib/python3.7/site-packages/stellar_sdk/xdr/StellarXDR_pack.py", line 2380, in unpack_PublicKeyType
    raise XDRError("value=%s not in enum PublicKeyType" % data)
xdrlib.Error: value=2 not in enum PublicKeyType
```
after an upgrade of the stellar sdk: `pip install stellar-sdk==2.6.1`, it worked again

**Comment by robvanmieghem** [comment]
- [ ] Normal conversion without locked tokens
- [ ] conversion with locked tokens
- [ ] tx funding service
- [ ] activation service
- [ ] unlock service
- [ ] jsx client

**Comment by robvanmieghem** [comment]
upgradedf the stellar sdk on both the testnet  and production environments since https://github.com/threefoldfoundation/tft-stellar/issues/171
