### ISSUE TITLE
error when passing an invalid address to the jsng activation servicre

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#220]
request:
```
curl -v -H "Content-Type: application/json" --insecure -d '{ "address": "<newaddress>"  }' "https://localhost:443/threefoldfoundation/activation_service/create_activation_code"
```
response:
```
< HTTP/1.1 500 Internal Server Error>
{"error": "an integer is required (got type bytes)"}
```

**Comment by ranatrk** [comment]
@robvanmieghem what was the type of newaddress passed as we can't seem to reproduce the same exact error message? Since the error indicates an integer is expected which isnt the case for the actor method being called, maybe the int expected is a propagated error.

**Comment by robvanmieghem** [comment]
@ranatrk , the error from within the jsng console:
```
2020-09-25 09:46:08.398 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method create_activation_code from actor activation_service_activation_service to client ('127.0.0.1', 50552)
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-N5daMEp6-py3.8/lib/python3.8/site-packages/stellar_sdk/strkey.py", line 221, in decode_check
    decoded_data = base64.b32decode(encoded_data)
  File "/usr/lib/python3.8/base64.py", line 205, in b32decode
    raise binascii.Error('Incorrect padding')
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-N5daMEp6-py3.8/lib/python3.8/site-packages/stellar_sdk/strkey.py", line 59, in decode_ed25519_public_key
    return decode_check("ed25519_public_key", data)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-N5daMEp6-py3.8/lib/python3.8/site-packages/stellar_sdk/strkey.py", line 223, in decode_check
    raise ValueError("Incorrect padding.")
stellar_sdk.exceptions.ValueError: Incorrect padding.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/root/sandbox/code/github/threefoldfoundation/tft-stellar/ng-pkgs/activation_service/sals/activation_sal.py", line 11, in _activate_account
    j.clients.stellar.activation_wallet.activate_account(address, starting_balance="3.6")
  File "/code/js-sdk/jumpscale/clients/stellar/stellar.py", line 262, in activate_account
    stellar_sdk.TransactionBuilder(
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-N5daMEp6-py3.8/lib/python3.8/site-packages/stellar_sdk/transaction_builder.py", line 293, in append_create_account_op
    op = CreateAccount(destination, starting_balance, source)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-N5daMEp6-py3.8/lib/python3.8/site-packages/stellar_sdk/operation/create_account.py", line 37, in __init__
    check_ed25519_public_key(destination)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-N5daMEp6-py3.8/lib/python3.8/site-packages/stellar_sdk/operation/utils.py", line 22, in check_ed25519_public_key
    Keypair.from_public_key(public_key)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-N5daMEp6-py3.8/lib/python3.8/site-packages/stellar_sdk/keypair.py", line 76, in from_public_key
    key = StrKey.decode_ed25519_public_key(public_key)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-N5daMEp6-py3.8/lib/python3.8/site-packages/stellar_sdk/strkey.py", line 61, in decode_ed25519_public_key
    raise Ed25519PublicKeyInvalidError(
stellar_sdk.exceptions.Ed25519PublicKeyInvalidError: Invalid Ed25519 Public Key: <newaddress>
2020-09-25T07:46:09Z <Greenlet at 0x7f98b89e56a0: _activate_account('<newaddress>')> failed with Ed25519PublicKeyInvalidError

127.0.0.1 - - [2020-09-25 09:46:09] "POST /activation_service/activation_service/create_activation_code HTTP/1.0" 500 198 1.347976
```
