### ISSUE TITLE
Error can't make transactions on testnet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldfoundation/tft-stellar#250]
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='horizon-testnet.stellar.org', port=443): Max retries exceeded with url: /transactions (Caused by ReadTimeoutError("HTTPSConnectionPool(host='horizon-testnet.stellar.org', port=443): Read timed out. (read timeout=20)"))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/waleed/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 202, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f9f29ebc160>
    └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7f9f293e2070>

  File "/home/waleed/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 210, in _execute_current_step
    wrapper(step_name)
    │       └ 'reserve_pool'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f9f289cfb80>

> File "/home/waleed/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
            │     └ 'reserve_pool'
            └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7f9f293e2070>

  File "/home/waleed/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<tfgrid_solutions.chats.pools.PoolReservation object at 0x7f9f293e2070>,)
           └ <function PoolReservation.reserve_pool at 0x7f9f2969daf0>

  File "/home/waleed/js-sdk/jumpscale/packages/tfgrid_solutions/chats/pools.py", line 47, in reserve_pool
    self.pool_data = deployer.create_pool(self)
    │                │        │           └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7f9f293e2070>
    │                │        └ <function ChatflowDeployer.create_pool at 0x7f9f2975ac10>
    │                └ <jumpscale.sals.reservation_chatflow.deployer.ChatflowDeployer object at 0x7f9f29753940>
    └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7f9f293e2070>

  File "/home/waleed/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 450, in create_pool
    qr_code = self.show_payment(pool_info, bot)
              │    │            │          └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7f9f293e2070>
              │    │            └ PoolCreated(
              │    │                reservation_id=7078,
              │    │                escrow_information=PoolEscrow(
              │    │                address='GCPPLQP27OXS6NVOFZZ5I4YUNWCLHFA32N2MBZKA7G52P...
              │    └ <function ChatflowDeployer.show_payment at 0x7f9f2975adc0>
              └ <jumpscale.sals.reservation_chatflow.deployer.ChatflowDeployer object at 0x7f9f29753940>

  File "/home/waleed/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 563, in show_payment
    wallet.transfer(
    │      └ <function Stellar.transfer at 0x7f9f30d004c0>
    └ Stellar(
        instance_name='demos_wallet2',
        network=<Network.TEST: 'TEST'>,
        address='GDBFSWXQCBWB6ULZ3IP2TQ6PC2KFXGV4IMCYW3...

  File "/home/waleed/js-sdk/jumpscale/clients/stellar/stellar.py", line 452, in transfer
    response = horizon_server.submit_transaction(transaction)
               │              │                  └ <stellar_sdk.transaction_envelope.TransactionEnvelope object at 0x7f9f28af8160>
               │              └ <function Server.submit_transaction at 0x7f9f30d704c0>
               └ <jumpscale.clients.stellar.wrapped.Server object at 0x7f9f28080eb0>

  File "/home/waleed/js-sdk/jumpscale/clients/stellar/wrapped.py", line 34, in submit_transaction
    return super().submit_transaction(transaction_envelope)
                                      └ <stellar_sdk.transaction_envelope.TransactionEnvelope object at 0x7f9f28af8160>

  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/stellar_sdk/server.py", line 108, in submit_transaction
    return self.__submit_transaction_sync(
           └ <jumpscale.clients.stellar.wrapped.Server object at 0x7f9f28080eb0>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/stellar_sdk/server.py", line 124, in __submit_transaction_sync
    resp = self._client.post(url=url, data=data)
           │    │       │    │   │    │    └ {'tx': 'AAAAAAXcCmn/h2wY5HPRW8EYkz9dob+sCXwFDL0tihU8CbfkAAAAyAAAAd4AAAAEAAAAAQAAAAAAAAAAAAAAAF/ZBIIAAAABAAAABnAtNzA3OAAAAAAAA...
           │    │       │    │   │    └ {'tx': 'AAAAAAXcCmn/h2wY5HPRW8EYkz9dob+sCXwFDL0tihU8CbfkAAAAyAAAAd4AAAAEAAAAAQAAAAAAAAAAAAAAAF/ZBIIAAAABAAAABnAtNzA3OAAAAAAAA...
           │    │       │    │   └ 'https://horizon-testnet.stellar.org/transactions'
           │    │       │    └ 'https://horizon-testnet.stellar.org/transactions'
           │    │       └ <function RequestsClient.post at 0x7f9f31463430>
           │    └ <stellar_sdk.client.requests_client.RequestsClient object at 0x7f9f293a7eb0>
           └ <jumpscale.clients.stellar.wrapped.Server object at 0x7f9f28080eb0>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/stellar_sdk/client/requests_client.py", line 139, in post
    raise ConnectionError(err)
          └ <class 'stellar_sdk.exceptions.ConnectionError'>

stellar_sdk.exceptions.ConnectionError: HTTPSConnectionPool(host='horizon-testnet.stellar.org', port=443): Max retries exceeded with url: /transactions (Caused by ReadTimeoutError("HTTPSConnectionPool(host='horizon-testnet.stellar.org', port=443): Read timed out. (read timeout=20)"))
```

**Comment by DylanVerstraete** [comment]
A wrapper function should wrap any function that submits a transaction to stellar with a retry if the error was 504 timeout.

**Comment by robvanmieghem** [comment]
Testnet works again now
