### ISSUE TITLE
vesting_dashboard does not show vesting accounts

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#311]
it crashes internally:
```
Traceback (most recent call last):
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.9/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.9/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/packages/auth/bottle/auth.py", line 370, in decorator
    return func(*args, **kwargs)
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/ThreeBotPackages/vesting_dashboard/bottle/vesting_dashboard.py", line 99, in list_vesting_accounts
    vesting_account_balances = _get_balance_details(tmp_wallet.get_balance(account.vesting_address))
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/clients/stellar/stellar.py", line 155, in get_balance
    for account in self._find_escrow_accounts(address):
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/clients/stellar/stellar.py", line 173, in _find_escrow_accounts
    new_cursor = parse.parse_qs(next_link_query)["cursor"][0]
    ```

**Comment by robvanmieghem** [comment]
Has to do with unexisting accounts and improper handling of empty cursor in the next link i js-sdk

**Comment by robvanmieghem** [comment]
the next link has been solved already
