### ISSUE TITLE
the vesting dashboard can not handle  cleaned up ( removed) vesting accounts

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#322]
```
File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.9/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.9/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/packages/auth/bottle/auth.py", line 370, in decorator
    return func(*args, **kwargs)
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/ThreeBotPackages/vesting_dashboard/bottle/vesting_dashboard.py", line 100, in list_vesting_accounts
    if payment.balance.asset_code != "TFT" or payment.payment_type != "payment":
AttributeError: 'NoneType' object has no attribute 'asset_code'
```

**Comment by robvanmieghem** [comment]
when the previous error is handled:
```
Traceback (most recent call last):
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.9/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.9/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/packages/auth/bottle/auth.py", line 370, in decorator
    return func(*args, **kwargs)
  File "/Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/ThreeBotPackages/vesting_dashboard/bottle/vesting_dashboard.py", line 110, in list_vesting_accounts
    vesting_account_balances = _get_balance_details(tmp_wallet.get_balance(account.vesting_address))
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/clients/stellar/stellar.py", line 155, in get_balance
    all_balances = self._get_free_balances(address)
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/clients/stellar/stellar.py", line 90, in _get_free_balances
    response = self._get_horizon_server().accounts().account_id(address).call()
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.9/lib/python3.9/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 58, in call
    return self.__call(url, self.params)
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.9/lib/python3.9/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 64, in __call
    return self.__call_sync(url, params)
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.9/lib/python3.9/site-packages/stellar_sdk/call_builder/base_call_builder.py", line 68, in __call_sync
    raise_request_exception(raw_resp)
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.9/lib/python3.9/site-packages/stellar_sdk/exceptions.py", line 207, in raise_request_exception
    raise NotFoundError(response)
stellar_sdk.exceptions.NotFoundError: {
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}
```
