### ISSUE TITLE
panic when aggregating unvesting signatures

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#486]
```log
% ./unvesting aggregate --dir in --network test
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
threefoldtech/unvesting/cmd.aggregateSignatures.func2({0x1400012d3a0, 0xc}, {0x10482ca78?, 0x1400012a880?}, {0x0?, 0x0?})
        /Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/unvesting/cmd/aggregate.go:58 +0x20c
path/filepath.walkDir({0x1400012d3a0, 0xc}, {0x10482ca78, 0x1400012a880}, 0x14000169b78)
        /usr/local/go/src/path/filepath/path.go:445 +0x44
path/filepath.walkDir({0x16b8c750c, 0x3}, {0x10482cab0, 0x14000116710}, 0x14000169b78)
        /usr/local/go/src/path/filepath/path.go:467 +0x224
path/filepath.WalkDir({0x16b8c750c, 0x3}, 0x14000169b78)
        /usr/local/go/src/path/filepath/path.go:535 +0xb0
threefoldtech/unvesting/cmd.aggregateSignatures({0x104759d8c, 0x1a}, {0x16b8c751a?, 0x0?}, {0x16b8c750c, 0x3}, {0x10475db2a, 0x21})
        /Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/unvesting/cmd/aggregate.go:40 +0x168
threefoldtech/unvesting/cmd.glob..func2(0x1049c1940?, {0x1400012a440?, 0x0?, 0x4?})
        /Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/unvesting/cmd/cmd.go:37 +0x5c
github.com/spf13/cobra.(*Command).execute(0x1049c1940, {0x1400012a3c0, 0x4, 0x4})
        /Users/rob/workspace/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x1049c1380)
        /Users/rob/workspace/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/rob/workspace/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
threefoldtech/unvesting/cmd.Execute()
        /Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/unvesting/cmd/cmd.go:60 +0x2d8
main.main()
        /Users/rob/sandbox/code/github/threefoldfoundation/tft-stellar/unvesting/main.go:8 +0x1c
```

**Comment by robvanmieghem** [comment]
bd342f426c8a7f846846a9a85b6ac863ea548be8
